env:
  browser: true
  es6: true
  es2020: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - airbnb
  - 'plugin:prettier/recommended'
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - jest
  - react
  - react-hooks
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - ./.storybook/*.?s*
        - ./backstop_data/**/*.?s*
        - ./src/__tests__/*.?s*
        - ./src/gulp/*.?s*
        - ./src/stories/*.?s*
        - ./main.?s
        - gulpfile.?s
        - '*.config.?s'
        - '*.stories.?s'
  no-console:
    - warn
  react/jsx-filename-extension:
    - 2
    - extensions:
        - .jsx
        - .tsx
  react/prop-types:
    - 'off'
settings:
  import/resolver:
    webpack:
      config: ./webpack.config.ts
