env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - airbnb
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
  - react
rules:
  react/jsx-filename-extension:
    - 2
    - extensions:
        - .jsx
        - .tsx
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - ./.storybook/*.?s*
        - ./backstop_data/**/*.?s*
        - ./src/__tests__/*.?s*
        - ./*.config.?s
        - ./main.?s
        - ./stories/*.?s
settings:
  import/resolver:
    webpack:
      config: ./webpack.config.ts
