version: 2.1
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: electronuserland/builder:wine-chrome
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       - v1-dependencies-
      # - run: npm install
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm test
      # - run: npm run build:binary
      # - run: npm run build:binary
# TODO: for Mac build
